name: Run EPL Script

on:
  schedule:
    # Runs at 7:00 PM EST every Monday (EST is UTC-5 or UTC-4 depending on DST)
    - cron: '00 23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip install -r requirements.txt

    # Set up Firebase Credentials from GitHub Secret
    - name: Set up Firebase credentials
      run: echo "$FIREBASE_SERVICE_ACCOUNT" > firebase-key.json
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        PL_DATA_API_KEY: ${{ secrets.PL_DATA_API_KEY }}

    - name: Run script
      run: python main-api.py
